version: '3.8'

services:
  nest-users:
    build: .
    container_name: api
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_NAME: ${POSTGRES_NAME}
      NODE_ENV: ${NODE_ENV}
    networks:
      - users-network

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - users-network

networks:
  users-network:
    name: users-network
    driver: bridge
    external: true
